using MoneyWise.Models;
using System.Text.Json;
using System.Text;

namespace MoneyWise.Services
{
    public class SavingsService
    {
        private readonly SupabaseService _supabaseService;
        private readonly UserRepository _userRepository;

        public SavingsService(SupabaseService supabaseService, UserRepository userRepository)
        {
            _supabaseService = supabaseService;
            _userRepository = userRepository;
        }

        public async Task<Savings?> GetUserSavingsAsync(string userEmail)
        {
            try
            {
                // Get user from database
                var users = await _userRepository.GetAllUsers();
                var user = users.FirstOrDefault(u => u.Email == userEmail);
                
                if (user == null)
                {
                    return null;
                }

                // Get savings from Supabase
                return await _supabaseService.GetSavingsByUserIdAsync(user.UserID);
            }
            catch (Exception)
            {
                return null;
            }
        }

        public async Task<bool> CreateSavingsAsync(Savings savings)
        {
            try
            {
                return await _supabaseService.CreateSavingsAsync(savings);
            }
            catch (Exception)
            {
                return false;
            }
        }

        public async Task<bool> UpdateSavingsAsync(int savingsId, Savings savings)
        {
            try
            {
                return await _supabaseService.UpdateSavingsAsync(savingsId, savings);
            }
            catch (Exception)
            {
                return false;
            }
        }

        public async Task<(bool success, string message)> SaveUserSavingsAsync(string userEmail, SavingsRequest request)
        {
            try
            {
                if (string.IsNullOrEmpty(userEmail))
                {
                    return (false, "User not authenticated");
                }

                // Get user from database
                var users = await _userRepository.GetAllUsers();
                
                // Add debugging
                Console.WriteLine($"Looking for user with email: {userEmail}");
                Console.WriteLine($"Total users in database: {users.Count}");
                foreach (var User in users)
                {
                    Console.WriteLine($"User in DB: {User.Email}");
                }
                
                var user = users.FirstOrDefault(u => u.Email == userEmail);
                
                if (user == null)
                {
                    return (false, $"User not found. Email: {userEmail}");
                }

                // Create new savings transaction
                var savings = new Savings
                {
                    TransactionID = 0, // Auto-generated by database
                    UserID = user.UserID,
                    Amount = request.Action == "deposit" ? request.SavingsAmount : -request.SavingsAmount,
                    created_at = DateTime.UtcNow
                };

                var success = await CreateSavingsAsync(savings);
                
                if (success)
                {
                    var actionText = request.Action == "deposit" ? "deposited" : "withdrawn";
                    return (true, $"₱{request.SavingsAmount:F2} successfully {actionText}.");
                }
                else
                {
                    return (false, "Failed to process transaction");
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Exception in SaveUserSavingsAsync: {ex.Message}");
                return (false, "An error occurred while processing the transaction");
            }
        }
    }
} 