using System.Text;
using System.Text.Json;
using MoneyWise.Models;

namespace MoneyWise.Services
{
    public class TransactionService
    {
        private readonly HttpClient _httpClient;
        private readonly UserRepository _userRepository;
        private readonly string _supabaseUrl;
        private readonly string _supabaseApiKey;

        public TransactionService(UserRepository userRepository, IConfiguration configuration)
        {
            _supabaseUrl = configuration["Authentication:Supabase:Url"]!;
            _supabaseApiKey = configuration["Authentication:Supabase:ApiKey"]!;
            _httpClient = new HttpClient
            {
                BaseAddress = new Uri(_supabaseUrl)
            };
            _httpClient.DefaultRequestHeaders.Add("apikey", _supabaseApiKey);
            _httpClient.DefaultRequestHeaders.Add("Authorization", $"Bearer {_supabaseApiKey}");
            _userRepository = userRepository;
        }

        public async Task<List<Savings>> GetUserTransactionsAsync(string userEmail)
        {
            try
            {
                // Get user from database first
                var users = await _userRepository.GetAllUsers();
                var user = users.FirstOrDefault(u => u.Email == userEmail);
                
                if (user == null)
                {
                    return new List<Savings>();
                }

                var response = await _httpClient.GetAsync($"/rest/v1/Savings?UserID=eq.{user.UserID}&select=*&order=created_at.desc");
                response.EnsureSuccessStatusCode();
                var json = await response.Content.ReadAsStringAsync();
                return JsonSerializer.Deserialize<List<Savings>>(json) ?? new List<Savings>();
            }
            catch (Exception)
            {
                return new List<Savings>();
            }
        }

        public async Task<Savings?> GetTransactionByIdAsync(int transactionId)
        {
            try
            {
                var response = await _httpClient.GetAsync($"/rest/v1/Savings?TransactionID=eq.{transactionId}&select=*");
                response.EnsureSuccessStatusCode();
                var json = await response.Content.ReadAsStringAsync();
                return JsonSerializer.Deserialize<List<Savings>>(json)?.FirstOrDefault();
            }
            catch (Exception)
            {
                return null;
            }
        }

        public async Task<bool> CreateTransactionAsync(Savings transaction)
        {
            var json = JsonSerializer.Serialize(transaction);
            var content = new StringContent(json, Encoding.UTF8, "application/json");
            var response = await _httpClient.PostAsync("/rest/v1/Savings", content);
            return response.IsSuccessStatusCode;
        }

        public async Task<bool> UpdateTransactionAsync(int id, Savings transaction)
        {
            var json = JsonSerializer.Serialize(transaction);
            var content = new StringContent(json, Encoding.UTF8, "application/json");
            var request = new HttpRequestMessage(new HttpMethod("PATCH"), $"/rest/v1/Savings?TransactionID=eq.{id}")
            {
                Content = content
            };
            var response = await _httpClient.SendAsync(request);
            return response.IsSuccessStatusCode;
        }

        public async Task<bool> DeleteTransactionAsync(int id)
        {
            try
            {
                var response = await _httpClient.DeleteAsync($"/rest/v1/Savings?TransactionID=eq.{id}");
                return response.IsSuccessStatusCode;
            }
            catch (Exception)
            {
                return false;
            }
        }

        public async Task<(bool success, string message)> SaveUserTransactionAsync(string? userEmail, TransactionRequest request)
        {
            try
            {
                if (string.IsNullOrEmpty(userEmail))
                {
                    return (false, "User not authenticated");
                }

                // Get user from database
                var users = await _userRepository.GetAllUsers();
                var user = users.FirstOrDefault(u => u.Email == userEmail);
                
                if (user == null)
                {
                    return (false, "User not found");
                }

                // Create transaction in Savings table
                var transaction = new Savings
                {
                    TransactionID = 0, // Auto-generated by database
                    UserID = user.UserID,
                    Amount = (decimal)request.Amount,
                    created_at = DateTime.UtcNow
                };

                var success = await CreateTransactionAsync(transaction);
                
                if (success)
                {
                    var actionText = request.Action == "add" ? "added to" : "withdrawn from";
                    return (true, $"₱{Math.Abs(request.Amount):F2} successfully {actionText} your savings.");
                }
                else
                {
                    return (false, "Failed to save transaction");
                }
            }
            catch (Exception)
            {
                return (false, "An error occurred while saving the transaction");
            }
        }

        // New methods for enhanced transaction history functionality

        public async Task<List<Savings>> GetRecentTransactionsAsync(string userEmail, int count = 10)
        {
            try
            {
                var users = await _userRepository.GetAllUsers();
                var user = users.FirstOrDefault(u => u.Email == userEmail);
                
                if (user == null)
                {
                    return new List<Savings>();
                }

                var response = await _httpClient.GetAsync($"/rest/v1/Savings?UserID=eq.{user.UserID}&select=*&order=created_at.desc&limit={count}");
                response.EnsureSuccessStatusCode();
                var json = await response.Content.ReadAsStringAsync();
                return JsonSerializer.Deserialize<List<Savings>>(json) ?? new List<Savings>();
            }
            catch (Exception)
            {
                return new List<Savings>();
            }
        }

        public async Task<List<Savings>> GetTransactionsByDateRangeAsync(string userEmail, DateTime startDate, DateTime endDate)
        {
            try
            {
                var users = await _userRepository.GetAllUsers();
                var user = users.FirstOrDefault(u => u.Email == userEmail);
                
                if (user == null)
                {
                    return new List<Savings>();
                }

                var startDateStr = startDate.ToString("yyyy-MM-dd");
                var endDateStr = endDate.ToString("yyyy-MM-dd");
                
                var response = await _httpClient.GetAsync($"/rest/v1/Savings?UserID=eq.{user.UserID}&created_at=gte.{startDateStr}&created_at=lte.{endDateStr}&select=*&order=created_at.desc");
                response.EnsureSuccessStatusCode();
                var json = await response.Content.ReadAsStringAsync();
                return JsonSerializer.Deserialize<List<Savings>>(json) ?? new List<Savings>();
            }
            catch (Exception)
            {
                return new List<Savings>();
            }
        }

        public async Task<TransactionStatistics> GetTransactionStatisticsAsync(string userEmail, DateTime? startDate = null, DateTime? endDate = null)
        {
            try
            {
                var transactions = await GetUserTransactionsAsync(userEmail);
                
                if (startDate.HasValue && endDate.HasValue)
                {
                    transactions = transactions.Where(t => t.created_at >= startDate && t.created_at <= endDate).ToList();
                }

                var deposits = transactions.Where(t => t.Amount >= 0).ToList();
                var withdrawals = transactions.Where(t => t.Amount < 0).ToList();

                return new TransactionStatistics
                {
                    TotalTransactions = transactions.Count,
                    TotalDeposits = (float)deposits.Sum(t => t.Amount),
                    TotalWithdrawals = (float)Math.Abs(withdrawals.Sum(t => t.Amount)),
                    NetBalance = (float)transactions.Sum(t => t.Amount),
                    AverageDeposit = deposits.Any() ? (float)deposits.Average(t => t.Amount) : 0,
                    AverageWithdrawal = withdrawals.Any() ? (float)Math.Abs(withdrawals.Average(t => t.Amount)) : 0,
                    LargestDeposit = deposits.Any() ? (float)deposits.Max(t => t.Amount) : 0,
                    LargestWithdrawal = withdrawals.Any() ? (float)Math.Abs(withdrawals.Min(t => t.Amount)) : 0
                };
            }
            catch (Exception)
            {
                return new TransactionStatistics();
            }
        }

        public async Task<List<MonthlyTransactionSummary>> GetMonthlyTransactionSummaryAsync(string userEmail, int year)
        {
            try
            {
                var transactions = await GetUserTransactionsAsync(userEmail);
                var yearTransactions = transactions.Where(t => t.created_at?.Year == year).ToList();

                var monthlySummaries = new List<MonthlyTransactionSummary>();
                
                for (int month = 1; month <= 12; month++)
                {
                    var monthTransactions = yearTransactions.Where(t => t.created_at?.Month == month).ToList();
                    var deposits = monthTransactions.Where(t => t.Amount >= 0).Sum(t => t.Amount);
                    var withdrawals = Math.Abs(monthTransactions.Where(t => t.Amount < 0).Sum(t => t.Amount));
                    
                    monthlySummaries.Add(new MonthlyTransactionSummary
                    {
                        Month = month,
                        MonthName = new DateTime(year, month, 1).ToString("MMMM"),
                        TotalDeposits = (float)deposits,
                        TotalWithdrawals = (float)withdrawals,
                        NetAmount = (float)(deposits - withdrawals),
                        TransactionCount = monthTransactions.Count
                    });
                }

                return monthlySummaries;
            }
            catch (Exception)
            {
                return new List<MonthlyTransactionSummary>();
            }
        }

        public async Task<TransactionHistoryResponse> GetTransactionHistoryAsync(string userEmail, TransactionHistoryFilter? filter = null)
        {
            try
            {
                var transactions = await GetUserTransactionsAsync(userEmail);
                
                if (filter != null)
                {
                    // Apply date range filter
                    if (filter.StartDate.HasValue)
                    {
                        transactions = transactions.Where(t => t.created_at >= filter.StartDate.Value).ToList();
                    }
                    
                    if (filter.EndDate.HasValue)
                    {
                        transactions = transactions.Where(t => t.created_at <= filter.EndDate.Value).ToList();
                    }

                    // Apply amount range filter
                    if (filter.MinAmount.HasValue)
                    {
                        transactions = transactions.Where(t => Math.Abs((float)t.Amount) >= filter.MinAmount.Value).ToList();
                    }
                    
                    if (filter.MaxAmount.HasValue)
                    {
                        transactions = transactions.Where(t => Math.Abs((float)t.Amount) <= filter.MaxAmount.Value).ToList();
                    }

                    // Apply transaction type filter
                    if (!string.IsNullOrEmpty(filter.TransactionType))
                    {
                        if (filter.TransactionType.ToLower() == "deposit")
                        {
                            transactions = transactions.Where(t => t.Amount >= 0).ToList();
                        }
                        else if (filter.TransactionType.ToLower() == "withdrawal")
                        {
                            transactions = transactions.Where(t => t.Amount < 0).ToList();
                        }
                    }
                }

                var statistics = await GetTransactionStatisticsAsync(userEmail);
                
                return new TransactionHistoryResponse
                {
                    Transactions = transactions,
                    Statistics = statistics,
                    TotalCount = transactions.Count
                };
            }
            catch (Exception)
            {
                return new TransactionHistoryResponse
                {
                    Transactions = new List<Savings>(),
                    Statistics = new TransactionStatistics(),
                    TotalCount = 0
                };
            }
        }
    }

    // Supporting classes for enhanced functionality
    public class TransactionStatistics
    {
        public int TotalTransactions { get; set; }
        public float TotalDeposits { get; set; }
        public float TotalWithdrawals { get; set; }
        public float NetBalance { get; set; }
        public float AverageDeposit { get; set; }
        public float AverageWithdrawal { get; set; }
        public float LargestDeposit { get; set; }
        public float LargestWithdrawal { get; set; }
    }

    public class MonthlyTransactionSummary
    {
        public int Month { get; set; }
        public string MonthName { get; set; } = string.Empty;
        public float TotalDeposits { get; set; }
        public float TotalWithdrawals { get; set; }
        public float NetAmount { get; set; }
        public int TransactionCount { get; set; }
    }

    public class TransactionHistoryFilter
    {
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public float? MinAmount { get; set; }
        public float? MaxAmount { get; set; }
        public string? TransactionType { get; set; } // "deposit" or "withdrawal"
    }

    public class TransactionHistoryResponse
    {
        public List<Savings> Transactions { get; set; } = new List<Savings>();
        public TransactionStatistics Statistics { get; set; } = new TransactionStatistics();
        public int TotalCount { get; set; }
    }
}